---
- name: Playbook to backup configs on Cisco Routers
  connection: local
  hosts: device_roles_router_redes
  gather_facts: False
  
  tasks:
    - name: Show running config on device
      ios_command:
        commands:
          - show run
      register: config
      
    - name: Save output to backups folder
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "./backups/{{ inventory_hostname }}-config.txt"
  vars:
    ansible_ssh_user: ansible
    ansible_ssh_password: ansible
    ansible_network_os: ios
    ansible_connection: network_cli
...

